Jest config changes and package.json for integration objects
SAP/cloud-sdk-currency-conversion pull request #40
Opened 2021-02-16 12:23 UTC by vidhyakpai

2021-02-16 13:29 UTC, marikaner commented on packages/integration-objects/package.json
> +    "compile": "cds build/all --clean && cds compile srv/ --to xsuaa  > cds-security.json",
```suggestion
    "compile": "exit 0 || cds build/all --clean && cds compile srv/ --to xsuaa  > cds-security.json",
```

2021-02-16 13:31 UTC, marikaner commented on packages/integration-objects/package.json
> +  "license": "ISC"
```suggestion
  "license": "Apache-2.0"
```

2021-02-16 13:38 UTC, marikaner requested changes
I adjusted the package.json, so that the integration-objects are not compiled. Please take care of this on a separate PR. It seems that the currently existing tests are not working. Please fix them before merging. If you think they should be fixed on a separate PR, disable the problematic tests and reenable on the fixing PR.

2021-02-16 15:09 UTC, vidhyakpai commented
@marikaner , the tests are failing due to the common files being checked in another PR https://github.com/SAP/cloud-sdk-currency-conversion/pull/29
I will push them in this PR too.

2021-02-16 15:21 UTC, vidhyakpai commented
@marikaner , I'd need to commit 5 repetitive files which are in the other PRs. Do you still want me to do it?

2021-02-16 16:19 UTC, marikaner commented
> @marikaner , I'd need to commit 5 repetitive files which are in the other PRs. Do you still want me to do it?

@vidhyakpai The state on main should always be tested and the tests should pass. You should never merge failing PRs, because that will break the main code line and most probably other PRs as well.
I can see that this is not just wrong configuration, but the productive code (that is currently on main) is broken, because there are files missing. When splitting changes into multiple PRs, please split it into logical units, where each change can be merged to the main code line without breaking it.

You added this PR (#40) to enable tests on #32, so that we can safely merge the changes. #32 will fail as well and you will not be able to fix this without fixing the main branch. If you are saying that there are only 5 files, I would suggest to add them to this PR (#40) (or a separate one if you think that is more appropriate).

Therefore, yes, let's find a way to make this green and only then merge more changes to the main code line.

2021-02-17 04:42 UTC, vidhyakpai commented
@marikaner , I have checked in the common files and commented out the 2 test cases that wouldn't run without the changes in the PR for this service and also checked in that file in this PR.

2021-02-17 09:14 UTC, marikaner commented on packages/integration-objects/srv/utils/ErrorStatuses.js
> +const ErrorStatuses = {
@vidhyakpai Consider renaming this to `ErrorStatus` because this is semantically an enum. (But don't do it now, add it to the renaming ticket ;) )

2021-02-17 09:17 UTC, marikaner commented on packages/integration-objects/srv/exceptions/validation-error.js
> +    this.code = code;
The error code here seems like a separate concern that should not be mixed with a `ValidationError`. It seems to be an HTTP status code, which is a totally different level of abstraction. However, let's not refactor it on this PR.

2021-02-17 09:18 UTC, marikaner approved these changes
Let's get the pipeline rolling!

2021-02-17 09:31 UTC, merged